version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/mini-todo
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
